name: Deploy to AWS

on:
    push:
      branches:
        - "main"

    
jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      
      - name: Config Aws Creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: eu-west-2

      - name: login to Amazon ECR
        id: login-ecr
        run: |
          echo "${{ secrets.SECRET_DOCKER_PASSWORD }}" | docker login --username "${{ secrets.SECETS_DOCKER_USERNAME }}" --password-stdin 117971648125.dkr.ecr.eu-west-2.amazonaws.com

