name: Deploy to AWS

on:
    push:
      branches:
        - "main"

    
jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      
      - name: Set Up Docker
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Log into Docker Registry
        run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 117971648125.dkr.ecr.eu-west-2.amazonaws.com
      
      - name: Build Docker Image
        run: docker -chdir=web build -t smtx_ecr .

